# Generated by Django 5.2.15 on 2026-06-29 22:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Código')),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('paid', 'Pagada'), ('confirmed', 'Confirmada'), ('scheduled', 'Programada'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='pending_payment', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_requests', to='companies.company', verbose_name='Empresa')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_requests', to='services.service', verbose_name='Servicio')),
                ('slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_request', to='scheduling.availabilityslot', verbose_name='Franja horaria')),
            ],
            options={
                'verbose_name': 'Solicitud de auditoría',
                'verbose_name_plural': 'Solicitudes de auditoría',
            },
        ),
    ]
