# Generated by Django 5.2.15 on 2026-06-30 03:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('coordination', 'Coordinación de auditoría'), ('quote', 'Cotización'), ('contact', 'Contacto')], max_length=20, verbose_name='Tipo')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('ruc', models.CharField(blank=True, max_length=11, verbose_name='RUC')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Cargo')),
                ('sedes', models.CharField(blank=True, max_length=255, verbose_name='Sedes')),
                ('audit_type', models.CharField(blank=True, choices=[('virtual', 'Virtual'), ('presencial', 'Presencial')], max_length=20, verbose_name='Tipo de auditoría')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('contacted', 'Contactada'), ('converted', 'Convertida'), ('closed', 'Cerrada')], default='new', max_length=20, verbose_name='Estado')),
                ('audit_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='audit_requests.auditrequest', verbose_name='Solicitud generada')),
            ],
            options={
                'verbose_name': 'Solicitud web',
                'verbose_name_plural': 'Solicitudes web',
            },
        ),
    ]
