# Generated by Django 5.2.15 on 2026-06-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(blank=True, help_text='Identificador de la pasarela de pago (p. ej. Stripe session id).', max_length=255, verbose_name='Referencia externa'),
        ),
    ]
