# Generated by Django 5.2.15 on 2026-06-29 22:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('blocked', 'Bloqueado'), ('booked', 'Reservado')], default='available', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Slot de disponibilidad',
                'verbose_name_plural': 'Slots de disponibilidad',
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('date', 'start_time', 'end_time'), name='unique_slot')],
            },
        ),
    ]
